netty:
  server:
    port: 8888
tencent:
  code-server:
    sdkAppId: xxxxxx #填入自己短信应用的sdkId
    templateId: xxxxxx #填入自己短信应用模板的Id
    phonePerfix: '+86'
  user-server:
    secretId: xxxxxxx #腾讯云应用的用户的密钥
    secretKey: xxxxxxxx #腾讯云应用的用户的密钥
    region: xxxxxxxxx
spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 30MB

  datasource:
    druid:
      username: root
      password: xxxxxx
      url: xxxxxx
      driver-class-name: com.mysql.cj.jdbc.Driver
      stat-view-servlet:
        url-pattern: /druid/*
        enabled: true
        login-username: xxxxx
        login-password: xxxx
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 1000
        wall:
          enabled: true
          config:
            drop-table-allow: false
            alter-table-allow: false
            select-into-outfile-allow: false
  jdbc:
    template:
      query-timeout: 3
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    client-type: jedis
    jedis:
      pool:
        enabled: true
        max-active: 10
  application:
    name: netdisc
  banner:
    image:
      location: banner.txt
mybatis-plus:
  config-location: classpath:mybatis.xml
logging:
  level:
    com:
      qzlnode: info
  file:
    name: /home/netdisc/execute.log